#!/bin/bash
cd /home/ec2-user/sites/qrsong
git reset --hard HEAD
git pull origin HEAD
sudo chmod +x deploy
sudo chmod +x deploy_api
sudo chmod +x deploy_frontend
sudo npm install --force
sudo prisma db push
echo "Repository has been reset and updated."
cd /home/ec2-user/sites/qrsong-frontend
git reset --hard HEAD
git pull origin HEAD
sudo npm install --force
sudo npm run build
npm run start