#!/bin/bash
cd /home/ec2-user/sites/qrsong

sudo chmod +x deploy
sudo chmod +x deploy_api
sudo chmod +x deploy_frontend

cd /home/ec2-user/sites/qrsong-frontend
git reset --hard HEAD
git pull origin HEAD
sudo npm install --force
sudo npm run build

pm2 restart qrsong-frontend

pm2 logs qrsong --lines 1000
