-- AlterTable: Add box product fields to payment_has_playlist
ALTER TABLE `payment_has_playlist`
  ADD COLUMN `boxEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `boxQuantity` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `boxPrice` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `boxFilename` VARCHAR(191) NULL,
  ADD COLUMN `boxFrontBackgroundType` VARCHAR(191) NULL DEFAULT 'image',
  ADD COLUMN `boxFrontBackground` VARCHAR(191) NULL,
  ADD COLUMN `boxFrontBackgroundColor` VARCHAR(191) NULL DEFAULT '#ffffff',
  ADD COLUMN `boxFrontUseFrontGradient` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `boxFrontGradientColor` VARCHAR(191) NULL DEFAULT '#ffffff',
  ADD COLUMN `boxFrontGradientDegrees` INTEGER NOT NULL DEFAULT 180,
  ADD COLUMN `boxFrontGradientPosition` INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN `boxFrontOpacity` INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN `boxFrontLogo` VARCHAR(191) NULL,
  ADD COLUMN `boxFrontEmoji` VARCHAR(191) NULL,
  ADD COLUMN `boxBackBackgroundType` VARCHAR(191) NULL DEFAULT 'solid',
  ADD COLUMN `boxBackBackground` VARCHAR(191) NULL,
  ADD COLUMN `boxBackBackgroundColor` VARCHAR(191) NULL DEFAULT '#ffffff',
  ADD COLUMN `boxBackFontColor` VARCHAR(191) NULL DEFAULT '#000000',
  ADD COLUMN `boxBackUseGradient` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `boxBackGradientColor` VARCHAR(191) NULL DEFAULT '#ffffff',
  ADD COLUMN `boxBackGradientDegrees` INTEGER NOT NULL DEFAULT 180,
  ADD COLUMN `boxBackGradientPosition` INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN `boxBackOpacity` INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN `boxBackText` TEXT NULL;
