// Generated by qrhit-api/scripts/sync-shared-data.mjs from locales.json,
// markets.json and currencies.json next to this file. Do not edit: change the
// JSON in qrhit-api/src/data/shared/ and run the script.

import localesJson from './locales.json';
import marketsJson from './markets.json';
import currenciesJson from './currencies.json';

export type LocaleCode = 'en' | 'nl' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'pl' | 'jp' | 'cn' | 'sv' | 'no' | 'da' | 'hu' | 'hin' | 'ru';
export type MarketCode = 'NL' | 'BE' | 'DE' | 'AT' | 'FR' | 'ES' | 'IT' | 'PT' | 'PL' | 'SE' | 'NO' | 'DK' | 'HU' | 'US' | 'GB' | 'JP' | 'CN' | 'AU' | 'CA' | 'CH' | 'IE' | 'CZ' | 'LI' | 'LU' | 'MC' | 'BR' | 'MX' | 'AR' | 'CL' | 'CO' | 'PE' | 'SM' | 'VA' | 'FI' | 'IS' | 'HK' | 'TW' | 'SG' | 'NZ' | 'ZA';
export type CurrencyCode = 'EUR' | 'NOK' | 'SEK' | 'DKK' | 'GBP' | 'CHF' | 'PLN' | 'CZK' | 'HUF' | 'USD' | 'CAD' | 'AUD';

export interface SharedLocale {
  code: LocaleCode;
  /** English name: LLM prompts, translate.js, and the `langs.<name in lower case>` key. */
  name: string;
  /** The name in the language itself: the language pickers. */
  nativeName: string;
  /** flagcdn.com country code. */
  flag: string;
  /** BCP-47 tag when the route code is not one (jp → ja). */
  htmlLang?: string;
  /** Codes a browser or device uses for this language (nb, nn → no). */
  aliases?: string[];
  ogLocale?: string;
  /** Mail greeting. */
  greeting?: string;
  /** Apple Music storefront. */
  storefront?: string;
  /** The market a speaker most likely buys from: payment methods. */
  country: MarketCode | null;
  /** The market whose dates the occasion pages use, when not `country`. */
  occasionCountry?: MarketCode;
  /** The currency this language's pages show, whoever crawls them. */
  currency: CurrencyCode | null;
  /** The countries the shipping page suggests first. */
  shippingCountries: string[];
  /** Mollie checkout locale (nl/de/fr vary by country in code). */
  mollieLocale: string | null;
  /** npm package with hyphenation patterns for card titles. */
  hyphenation: string | null;
  /** How the playlist prompt names the language and its market. */
  aiDescription?: string;
  /** Part of the product feed offer id; never renumber. */
  feedNumber?: number;
  /** Served by qrsong.io. */
  site: boolean;
  /** Spoken by the scan app. */
  app: boolean;
}

export interface SharedMarket {
  code: MarketCode;
  name: string;
  /** The currency a visitor from here gets unless they pick one (EUR when absent). */
  currency?: CurrencyCode;
  /** The playlist languages /playlists shows here, besides the international lists. */
  locales?: LocaleCode[];
  /** Mollie methods, most popular first; the checkout shows them in this order. */
  paymentMethods?: string[];
  /** Methods the homepage trust strip leaves out here. */
  notOnBadges?: string[];
  /** An occasion-calendar market. */
  occasions?: boolean;
  /** The language of this country's product feed, when it has one. */
  feed?: LocaleCode;
}

export interface SharedCurrency {
  code: CurrencyCode;
  /** Decimals a price is shown with. */
  decimals: number;
  /** Converted amounts round to a multiple of this (0: to the cent). */
  snap: number;
  /** Mollie methods that accept it. A method no currency lists is EUR-only. */
  methods: string[];
}

/** Every language, the unserved (site: false) ones included. */
export const LOCALES = localesJson.locales as unknown as readonly SharedLocale[];
/** The languages qrsong.io is served in, in menu order. */
export const SITE_LOCALES = LOCALES.filter((l) => l.site);
/** The languages the scan app speaks. */
export const APP_LOCALES = LOCALES.filter((l) => l.app);
export const MARKETS = marketsJson.markets as unknown as readonly SharedMarket[];
/** Payment methods for a visitor without a known country. */
export const PAYMENT_FALLBACK = marketsJson.fallback.paymentMethods as readonly string[];
/** In the currency switcher's order. */
export const CURRENCIES = currenciesJson.currencies as unknown as readonly SharedCurrency[];
