/**
 * Copy what the old AI asset generator made into the company asset store.
 *
 * The Assets tab used to generate rebranded product photos (Gemini and
 * OpenAI) into PUBLIC_DIR/companydata/assets/<companyId>/<assetId>/, from
 * branding images uploaded to .../branding_<ts>/. It is a plain store now
 * (CompanyFile, src/companyFiles.ts). This copies every generated image in as
 * category `generated` and every uploaded branding image as `brand`, both
 * with source `migrated`.
 *
 * Nothing is moved or deleted: the old files and the company_assets table
 * stay as they are, so going back is a deploy. Each copy carries a
 * `legacyKey`, so running it again skips what is already there.
 *
 *   npx tsx scripts/migrate-company-assets.ts          # report only
 *   npx tsx scripts/migrate-company-assets.ts --write  # copy
 *
 * Needs the company_files table: run `npx prisma db push` first.
 */
import 'dotenv/config';
import fs from 'fs/promises';
import path from 'path';
import { PrismaClient } from '@prisma/client';
import { saveCompanyFile } from '../src/companyFiles';

const write = process.argv.includes('--write');
const prisma = new PrismaClient();

interface Planned {
  companyId: number;
  source: string;
  legacyKey: string;
  category: 'generated' | 'brand';
  note: string;
}

function parseList(value: string | null): string[] {
  if (!value) return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed.filter((v) => typeof v === 'string') : [];
  } catch {
    return [];
  }
}

async function exists(file: string): Promise<boolean> {
  return fs
    .stat(file)
    .then((s) => s.isFile())
    .catch(() => false);
}

/** Branding uploads sit in branding_<ts>/ folders beside the asset folders. */
async function brandingFolders(companyDir: string): Promise<string[]> {
  const entries = await fs.readdir(companyDir, { withFileTypes: true }).catch(() => []);
  return entries
    .filter((e) => e.isDirectory() && e.name.startsWith('branding_'))
    .map((e) => path.join(companyDir, e.name));
}

async function main() {
  const publicDir = process.env['PUBLIC_DIR'];
  if (!publicDir || !process.env['PRIVATE_DIR']) {
    throw new Error('PUBLIC_DIR and PRIVATE_DIR must be set (.env)');
  }
  const assetsRoot = path.join(publicDir, 'companydata', 'assets');
  const assets = await prisma.companyAsset.findMany({ orderBy: { id: 'asc' } });
  const planned: Planned[] = [];
  const missing: string[] = [];

  for (const asset of assets) {
    const label = asset.label || `asset ${asset.id}`;
    for (const name of parseList(asset.images)) {
      const source = path.join(assetsRoot, String(asset.companyId), String(asset.id), name);
      if (!(await exists(source))) {
        missing.push(source);
        continue;
      }
      planned.push({
        companyId: asset.companyId,
        source,
        legacyKey: `company-asset:${asset.id}:${name}`,
        category: 'generated',
        note: `Generated by the old asset generator: ${label} (${asset.llmProvider})`,
      });
    }
  }

  const companyIds = [...new Set(assets.map((a) => a.companyId))];
  for (const companyId of companyIds) {
    for (const folder of await brandingFolders(path.join(assetsRoot, String(companyId)))) {
      const files = await fs.readdir(folder).catch(() => []);
      for (const name of files) {
        planned.push({
          companyId,
          source: path.join(folder, name),
          legacyKey: `company-branding:${companyId}:${path.basename(folder)}:${name}`,
          category: 'brand',
          note: 'Branding uploaded to the old asset generator',
        });
      }
    }
  }

  const done = new Set(
    (
      await prisma.companyFile.findMany({
        where: { legacyKey: { in: planned.map((p) => p.legacyKey) } },
        select: { legacyKey: true },
      })
    ).map((f) => f.legacyKey)
  );
  const todo = planned.filter((p) => !done.has(p.legacyKey));
  const existingCompanies = new Set(
    (await prisma.company.findMany({ where: { id: { in: companyIds } }, select: { id: true } })).map((c) => c.id)
  );

  console.log(`company_assets rows: ${assets.length}`);
  console.log(`files found: ${planned.length} (${planned.filter((p) => p.category === 'generated').length} generated, ${planned.filter((p) => p.category === 'brand').length} branding)`);
  console.log(`already in the store: ${done.size}`);
  console.log(`to copy: ${todo.length}`);
  if (missing.length) console.log(`listed but missing on disk: ${missing.length}`);

  if (!write) {
    for (const p of todo.slice(0, 20)) console.log(`  company ${p.companyId}  ${p.category.padEnd(9)}  ${p.source}`);
    if (todo.length > 20) console.log(`  … and ${todo.length - 20} more`);
    console.log('\nReport only. Run with --write to copy.');
    return;
  }

  let copied = 0;
  for (const p of todo) {
    if (!existingCompanies.has(p.companyId)) continue;
    const buffer = await fs.readFile(p.source);
    await saveCompanyFile(
      p.companyId,
      { buffer, originalName: path.basename(p.source) },
      { category: p.category, source: 'migrated', note: p.note, legacyKey: p.legacyKey }
    );
    copied++;
  }
  console.log(`copied: ${copied}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
